version: '3.8'

services:
  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./consumer:/app/consumer
    command: >
      bash -c "spark-submit
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1
      /app/consumer/spark_consumer.py"
    networks:
      - kafka-net

networks:
  kafka-net:
  external:
    name: kafka-net

